## 0. 코랩 마운트

In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [2]:
!unzip /content/drive/MyDrive/Lettuce_disease_diagnosis/crop_processed_data.zip -d /content/


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
  inflating: /content/crop_processed_data/lettuce_v1/train/0/V006_77_0_00_05_03_12_0_c29_20201126_0756_S01_1.jpg  
  inflating: /content/crop_processed_data/lettuce_v1/train/0/V006_77_0_00_05_03_12_0_c29_20201126_0761_S01_1.jpg  
  inflating: /content/crop_processed_data/lettuce_v1/train/0/V006_77_0_00_05_03_12_0_c29_20201126_0762_S01_1.jpg  
  inflating: /content/crop_processed_data/lettuce_v1/train/0/V006_77_0_00_05_03_12_0_c29_20201126_0763_S01_1.jpg  
  inflating: /content/crop_processed_data/lettuce_v1/train/0/V006_77_0_00_05_03_12_0_c29_20201126_0766_S01_1.jpg  
  inflating: /content/crop_processed_data/lettuce_v1/train/0/V006_77_0_00_05_03_12_0_c29_20201126_0768_S01_1.jpg  
  inflating: /content/crop_processed_data/lettuce_v1/train/0/v006_77_0_00_05_03_12_0_c29_20201126_0770_s01_1.jpg  
  inflating: /content/crop_processed_data/lettuce_v1/train/0/V006_77_0_00_05_03_12_0_c29_20201126_0771_S01_1.jpg  
  inflating: /content/crop_processed_data/le

In [ ]:
!ls /content/crop_processed_data
!ls /content/crop_processed_data/lettuce_v1


lettuce_v1
test  train  val


## 1.베이스, 최상위 성능 구하기

CNN 학습

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 256 \
  --num_workers 2 \
  --epochs 10

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/LETTUCE_bs256_lr0.001_20251114-084903
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=0.7689 val_loss=0.5786 val_acc=79.83% lr=1.000e-03 (331.7s)
Epoch 002 | train_loss=0.5358 val_loss=0.4343 val_acc=83.97% lr=1.000e-03 (355.0s)
Epoch 003 | train_loss=0.4702 val_loss=0.3874 val_acc=85.44% lr=1.000e-03 (361.0s)
Epoch 004 | train_loss=0.4306 val_loss=0.3467 val_acc=87.30% lr=1.000e-03 (336.1s)
Epoch 005 | train_loss=0.3997 val_loss=0.3182 val_acc=88.25% lr=1.000e-03 (329.0s)
Epoch 006 | train_loss=0.3690 val_loss=0.2937 val_acc=89.03% lr=1.000e-03 (338.8s)
Epoch 007 | train_loss=0.3492 val_loss=0.2838 val_acc=89.68% lr=1.000e-03 (328.1s)
Epoch 008 | train_loss=0.3264 val_loss=0.2706 val_acc=90.45% lr=1.000e-03 (328.8s)
Epoch 009 | train_loss=0.3065 val_loss=0.2623 val_acc=91.45% lr=1.000e-03 (327.4s)
Epoch 010 | train_loss=0.2920 val_loss=0.2500 val_acc=92.14% lr=1.000e-0

In [ ]:
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 256 \
  --num_workers 2 \
  --epochs 20 \
  --resume /content/drive/MyDrive/Lettuce_disease_diagnosis/runs_lettuce/LETTUCE_bs256_lr0.001_20251114-084903/last.pt


[Device] cuda
[Run dir] runs_lettuce/LETTUCE_bs256_lr0.001_20251114-095156
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
[Resume] Loaded checkpoint from /content/drive/MyDrive/Lettuce_disease_diagnosis/runs_lettuce/LETTUCE_bs256_lr0.001_20251114-084903/last.pt (start from epoch 11)
Epoch 011 | train_loss=0.2833 val_loss=0.2418 val_acc=91.66% lr=1.000e-03 (355.7s)
Epoch 012 | train_loss=0.2701 val_loss=0.2238 val_acc=91.66% lr=1.000e-03 (358.0s)
Epoch 013 | train_loss=0.2563 val_loss=0.2197 val_acc=92.31% lr=1.000e-03 (329.4s)
Epoch 014 | train_loss=0.2464 val_loss=0.2414 val_acc=92.22% lr=1.000e-03 (337.4s)
Epoch 015 | train_loss=0.2362 val_loss=0.2016 val_acc=93.22% lr=1.000e-03 (333.7s)
Epoch 016 | train_loss=0.2205 val_loss=0.1969 val_acc=93.26% lr=1.000e-03 (349.3s)
Epoch 017 | train_loss=0.2171 val_loss=0.2100 val_acc=92.18% lr=1.000e-03 (325.4s)
Epoch 018 | train_loss=0.2141 val_loss=0.2511 val_acc=89.98% lr=1.000e-03 (331.0s)
Epoch 019 | train_loss=0.2116 val_loss=0.1

ResNet 학습

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.RESNET18_train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 256 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/resnet18_full_bs256_lr0.001_20251114-105019
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100% 44.7M/44.7M [00:00<00:00, 176MB/s]
Epoch 001 | train_loss=0.5107 val_loss=0.2340 val_acc=90.84% lr=1.000e-03 (328.9s)
Epoch 002 | train_loss=0.1917 val_loss=0.1420 val_acc=94.82% lr=1.000e-03 (356.3s)
Epoch 003 | train_loss=0.1381 val_loss=0.1202 val_acc=95.64% lr=1.000e-03 (333.3s)
Epoch 004 | train_loss=0.1194 val_loss=0.1101 val_acc=95.94% lr=1.000e-03 (348.0s)
Epoch 005 | train_loss=0.1046 val_loss=0.1011 val_acc=96.29% lr=1.000e-03 (334.6s)
Epoch 006 | train_loss=0.1006 val_loss=0.0950 val_acc=96.41% lr=1.000e-03 (328.8s)
Epoch 007 | train_loss=0.0923 val_loss=0.0915 val_acc=96.59% lr=1.000e-03 (321.9s)
Epoch 008 | train_loss=0.0873 val_loss=0.0869 val_acc=96.76

CNN 평가

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model cnn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/LETTUCE_bs256_lr0.001_20251114-084903/best_ep016.pt \
  --num_classes 3 \
  --cm_path results/cnn_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : cnn
===== TEST RESULTS =====
Accuracy   : 0.9313
Precision  : 0.8894
Recall     : 0.8268
F1 Score   : 0.8543

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      2180
           1       0.78      0.74      0.76       335
           2       0.93      0.75      0.83       380

    accuracy                           0.93      2895
   macro avg       0.89      0.83      0.85      2895
weighted avg       0.93      0.93      0.93      2895


--- Confusion Matrix ---
[[2164   15    1]
 [  68  248   19]
 [  42   54  284]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/cnn_confusion_matrix.png


ResNet 평가

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model resnet18 \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/resnet18_full_bs256_lr0.001_20251114-105019/best_ep020.pt \
  --num_classes 3 \
  --cm_path results/resnet18_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : resnet18
===== TEST RESULTS =====
Accuracy   : 0.9744
Precision  : 0.9412
Recall     : 0.9334
F1 Score   : 0.9371

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2180
           1       0.89      0.90      0.89       335
           2       0.94      0.90      0.92       380

    accuracy                           0.97      2895
   macro avg       0.94      0.93      0.94      2895
weighted avg       0.97      0.97      0.97      2895


--- Confusion Matrix ---
[[2177    3    0]
 [  12  302   21]
 [   3   35  342]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/resnet18_confusion_matrix.png


## 2. 성능 향상 실험

## 실험1. Weight Loss 적용

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 256 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/LETTUCE_bs256_lr0.001_20251115-065805
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
[Weighted CE] class_counts: Counter({0: 6976, 2: 1215, 1: 1074})
[Weighted CE] class_weights: tensor([0.4427, 2.8755, 2.5418], device='cuda:0')
Epoch 001 | train_loss=0.9373 val_loss=0.8594 val_acc=71.97% val_f1=0.6409 lr=1.000e-03 (345.7s)
Epoch 002 | train_loss=0.7465 val_loss=0.6898 val_acc=75.59% val_f1=0.6722 lr=1.000e-03 (354.2s)
Epoch 003 | train_loss=0.6683 val_loss=0.6230 val_acc=75.25% val_f1=0.6830 lr=1.000e-03 (333.5s)
Epoch 004 | train_loss=0.6148 val_loss=0.5421 val_acc=81.47% val_f1=0.7297 lr=1.000e-03 (339.4s)
Epoch 005 | train_loss=0.5819 val_loss=0.4858 val_acc=82.85% val_f1=0.7477 lr=1.000e-03 (329.0s)
Epoch 006 | train_loss=0.5384 val_loss=0.4177 val_acc=86.95% val_f1=0.7887 lr=1.000e-03 (326.4s)
Epoch 007 | train_loss=0.5190 val_loss=0.3833 val_acc=88.38% val_f1=0.8032 lr=1.000e-03 (357.

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model cnn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/LETTUCE_bs256_lr0.001_20251115-065805/best_ep019.pt \
  --num_classes 3 \
  --cm_path results/cnn_confusion_matrix2.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : cnn
===== TEST RESULTS =====
Accuracy   : 0.9326
Precision  : 0.8729
Recall     : 0.8797
F1 Score   : 0.8655

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.98      0.97      0.97      2180
           1       0.68      0.93      0.78       335
           2       0.96      0.74      0.84       380

    accuracy                           0.93      2895
   macro avg       0.87      0.88      0.87      2895
weighted avg       0.94      0.93      0.93      2895


--- Confusion Matrix ---
[[2106   73    1]
 [  12  311   12]
 [  23   74  283]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/cnn_confusion_matrix2.png


## 실험2. oversampling

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 256 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/LETTUCE_bs256_lr0.001_20251115-085921
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=0.9347 val_loss=0.8264 val_acc=77.41% val_f1=0.6779 lr=1.000e-03 (327.5s)
Epoch 002 | train_loss=0.7246 val_loss=0.6562 val_acc=76.50% val_f1=0.6795 lr=1.000e-03 (330.2s)
Epoch 003 | train_loss=0.6654 val_loss=0.5892 val_acc=78.19% val_f1=0.7019 lr=1.000e-03 (324.7s)
Epoch 004 | train_loss=0.6086 val_loss=0.4957 val_acc=82.94% val_f1=0.7451 lr=1.000e-03 (319.0s)
Epoch 005 | train_loss=0.5836 val_loss=0.5195 val_acc=81.30% val_f1=0.7368 lr=1.000e-03 (324.9s)
Epoch 006 | train_loss=0.5297 val_loss=0.4330 val_acc=85.57% val_f1=0.7746 lr=1.000e-03 (327.0s)
Epoch 007 | train_loss=0.5128 val_loss=0.4400 val_acc=85.05% val_f1=0.7723 lr=1.000e-03 (320.6s)
Epoch 008 | train_loss=0.4969 val_loss=0.4159 val_acc=86.13% val_f1=0.7885 lr=1.000e-03 (319.3s)
Epoch 009 | train_loss=0.4559 val_loss=0.35

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model cnn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/LETTUCE_bs256_lr0.001_20251115-085921/best_ep019.pt \
  --num_classes 3 \
  --cm_path results/cnn_confusion_matrix3.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : cnn
===== TEST RESULTS =====
Accuracy   : 0.9406
Precision  : 0.8768
Recall     : 0.8945
F1 Score   : 0.8793

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.99      0.97      0.98      2180
           1       0.71      0.92      0.80       335
           2       0.93      0.79      0.86       380

    accuracy                           0.94      2895
   macro avg       0.88      0.89      0.88      2895
weighted avg       0.95      0.94      0.94      2895


--- Confusion Matrix ---
[[2113   59    8]
 [  13  308   14]
 [  11   67  302]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/cnn_confusion_matrix3.png


## 실험3. Custom CNN

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 256 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/LETTUCE_bs256_lr0.001_20251115-133801
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=1.0148 val_loss=0.9023 val_acc=78.36% val_f1=0.6901 lr=1.000e-03 (325.0s)
Epoch 002 | train_loss=0.7321 val_loss=0.5818 val_acc=79.05% val_f1=0.7029 lr=1.000e-03 (327.3s)
Epoch 003 | train_loss=0.6127 val_loss=0.5273 val_acc=80.99% val_f1=0.7347 lr=1.000e-03 (348.2s)
Epoch 004 | train_loss=0.5326 val_loss=0.4232 val_acc=85.40% val_f1=0.7780 lr=1.000e-03 (325.9s)
Epoch 005 | train_loss=0.4665 val_loss=0.4448 val_acc=82.89% val_f1=0.7558 lr=1.000e-03 (331.9s)
Epoch 006 | train_loss=0.4211 val_loss=0.2828 val_acc=89.07% val_f1=0.8165 lr=1.000e-03 (325.4s)
Epoch 007 | train_loss=0.3922 val_loss=0.3120 val_acc=87.95% val_f1=0.8082 lr=1.000e-03 (357.3s)
Epoch 008 | train_loss=0.3720 val_loss=0.3606 val_acc=86.35% val_f1=0.7963 lr=1.000e-03 (353.9s)
Epoch 009 | train_loss=0.3546 val_loss=0.27

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model resseattn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/LETTUCE_bs256_lr0.001_20251115-133801/best_ep020.pt \
  --num_classes 3 \
  --cm_path results/ResSEAttnCNN_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : resseattn
===== TEST RESULTS =====
Accuracy   : 0.9503
Precision  : 0.8857
Recall     : 0.9030
F1 Score   : 0.8939

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      2180
           1       0.80      0.86      0.83       335
           2       0.87      0.87      0.87       380

    accuracy                           0.95      2895
   macro avg       0.89      0.90      0.89      2895
weighted avg       0.95      0.95      0.95      2895


--- Confusion Matrix ---
[[2132   34   14]
 [  11  289   35]
 [  10   40  330]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/ResSEAttnCNN_confusion_matrix.png


## 3.XAI 적용

In [ ]:
!pip install grad-cam
!sudo apt-get update
!sudo apt-get install -y fonts-nanum



     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 42.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for grad-cam: filename=grad_cam-1.5.5-py3-none-any.whl size=44284 sha256=9695c30f3e7e049edb1ccab039d0c97b7b7568677e099fee0ae8ccc9e068813d
  Stored in directory: /root/.cache/pip/wheels/fb/3b/09/2afc520f3d69bc26ae6bd87416759c820a3f7d05c1a077bbf6
Successfully built grad-cam


In [ ]:
!fc-list | grep Nanum


/usr/share/fonts/truetype/nanum/NanumSquareRoundB.ttf: NanumSquareRound,나눔스퀘어라운드,NanumSquareRound Bold,나눔스퀘어라운드 Bold:style=Bold,Regular
/usr/share/fonts/truetype/nanum/NanumGothicCodingBold.ttf: NanumGothicCoding,나눔고딕코딩:style=Bold
/usr/share/fonts/truetype/nanum/NanumSquareRoundR.ttf: NanumSquareRound,나눔스퀘어라운드,NanumSquareRound Regular,나눔스퀘어라운드 Regular:style=Regular
/usr/share/fonts/truetype/nanum/NanumSquareB.ttf: NanumSquare,나눔스퀘어,NanumSquare Bold,나눔스퀘어 Bold:style=Bold
/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf: NanumBarunGothic,나눔바른고딕:style=Regular
/usr/share/fonts/truetype/nanum/NanumGothic.ttf: NanumGothic,나눔고딕:style=Regular
/usr/share/fonts/truetype/nanum/NanumGothicCoding.ttf: NanumGothicCoding,나눔고딕코딩:style=Regular
/usr/share/fonts/truetype/nanum/NanumBarunGothicBold.ttf: NanumBarunGothic,나눔바른고딕:style=Bold
/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf: NanumGothic,나눔고딕:style=Bold
/usr/share/fonts/truetype/nanum/NanumSquareR.ttf: NanumSquare,나눔스퀘어:style=Regular
/us

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.xai.run_rise --model-type resseattn


/content/drive/MyDrive/Lettuce_disease_diagnosis
[resseattn] 총 12장의 이미지를 RISE로 XAI 시각화합니다.
✅ Saved: result/xai_rise/ResSEAttnCNN/disease1_1_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/disease1_2_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/disease1_3_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/disease1_4_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/disease2_1_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/disease2_2_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/disease2_3_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/disease2_4_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/normal1_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/normal2_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/normal3_rise.jpg
✅ Saved: result/xai_rise/ResSEAttnCNN/normal4_rise.jpg

🎉 모든 RISE XAI 시각화 저장 완료


In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.xai.run_rise --model-type resnet

/content/drive/MyDrive/Lettuce_disease_diagnosis
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100% 44.7M/44.7M [00:00<00:00, 123MB/s]
[resnet] 총 12장의 이미지를 RISE로 XAI 시각화합니다.
✅ Saved: result/xai_rise/ResNet/disease1_1_rise.jpg
✅ Saved: result/xai_rise/ResNet/disease1_2_rise.jpg
✅ Saved: result/xai_rise/ResNet/disease1_3_rise.jpg
✅ Saved: result/xai_rise/ResNet/disease1_4_rise.jpg
✅ Saved: result/xai_rise/ResNet/disease2_1_rise.jpg
✅ Saved: result/xai_rise/ResNet/disease2_2_rise.jpg
✅ Saved: result/xai_rise/ResNet/disease2_3_rise.jpg
✅ Saved: result/xai_rise/ResNet/disease2_4_rise.jpg
✅ Saved: result/xai_rise/ResNet/normal1_rise.jpg
✅ Saved: result/xai_rise/ResNet/normal2_rise.jpg
✅ Saved: result/xai_rise/ResNet/normal3_rise.jpg
✅ Saved: result/xai_rise/ResNet/normal4_rise.jpg

🎉 모든 RISE XAI 시각화 저장 완료


## 4.. [ABLATION] Test

#### 0. 기존 모델 배치 크기 줄이기

In [3]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 128 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/ablation_test/ABL_reduce_batch_bs128_lr0.001_20251204-032651
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=0.8681 val_loss=0.6058 val_acc=77.06% val_f1=0.6844 lr=1.000e-03 (346.9s)
Epoch 002 | train_loss=0.5855 val_loss=0.3759 val_acc=87.99% val_f1=0.8015 lr=1.000e-03 (350.5s)
Epoch 003 | train_loss=0.4548 val_loss=0.3584 val_acc=87.13% val_f1=0.8015 lr=1.000e-03 (337.4s)
Epoch 004 | train_loss=0.3969 val_loss=0.4217 val_acc=82.33% val_f1=0.7533 lr=1.000e-03 (336.7s)
Epoch 005 | train_loss=0.3563 val_loss=0.2342 val_acc=91.45% val_f1=0.8448 lr=1.000e-03 (346.2s)
Epoch 006 | train_loss=0.3455 val_loss=0.1850 val_acc=93.22% val_f1=0.8637 lr=1.000e-03 (352.4s)
Epoch 007 | train_loss=0.3264 val_loss=0.1983 val_acc=92.83% val_f1=0.8644 lr=1.000e-03 (339.0s)
Epoch 008 | train_loss=0.3268 val_loss=0.2694 val_acc=90.24% val_f1=0.8291 lr=1.000e-03 (352.6s)
Epoch 009 | train_lo

In [4]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model resseattn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/ablation_test/ABL_reduce_batch_bs128_lr0.001_20251204-032651/best_ep020.pt \
  --batch_size 128 \
  --num_classes 3 \
  --cm_path results/ablation/full_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : resseattn
===== TEST RESULTS =====
Accuracy   : 0.9579
Precision  : 0.9071
Recall     : 0.9073
F1 Score   : 0.9035

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2180
           1       0.78      0.92      0.85       335
           2       0.95      0.81      0.87       380

    accuracy                           0.96      2895
   macro avg       0.91      0.91      0.90      2895
weighted avg       0.96      0.96      0.96      2895


--- Confusion Matrix ---
[[2156   20    4]
 [  13  309   13]
 [   6   66  308]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/ablation/full_confusion_matrix.png


#### 1. Spatial Attention 제거

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 128 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/ablation_test/ABL_sa_off_bs128_lr0.001_20251129-124645
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=0.8167 val_loss=0.6217 val_acc=76.63% val_f1=0.6864 lr=1.000e-03 (348.9s)
Epoch 002 | train_loss=0.5816 val_loss=0.4480 val_acc=83.97% val_f1=0.7604 lr=1.000e-03 (340.6s)
Epoch 003 | train_loss=0.4760 val_loss=0.4768 val_acc=80.30% val_f1=0.7437 lr=1.000e-03 (335.7s)
Epoch 004 | train_loss=0.4024 val_loss=0.3035 val_acc=88.08% val_f1=0.7983 lr=1.000e-03 (342.7s)
Epoch 005 | train_loss=0.3739 val_loss=0.2371 val_acc=91.32% val_f1=0.8455 lr=1.000e-03 (334.3s)
Epoch 006 | train_loss=0.3571 val_loss=0.2055 val_acc=92.57% val_f1=0.8582 lr=1.000e-03 (346.8s)
Epoch 007 | train_loss=0.3444 val_loss=0.1807 val_acc=93.05% val_f1=0.8586 lr=1.000e-03 (333.0s)
Epoch 008 | train_loss=0.3297 val_loss=0.3215 val_acc=88.29% val_f1=0.8117 lr=1.000e-03 (345.0s)
Epoch 009 | train_loss=0.3

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model resseattn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/ablation_test/ABL_sa_off_bs128_lr0.001_20251129-124645/best_ep020.pt \
  --batch_size 128 \
  --num_classes 3 \
  --cm_path results/ablation/withoutAttn_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : resseattn
===== TEST RESULTS =====
Accuracy   : 0.9541
Precision  : 0.9002
Recall     : 0.9119
F1 Score   : 0.8996

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      2180
           1       0.75      0.95      0.84       335
           2       0.96      0.80      0.87       380

    accuracy                           0.95      2895
   macro avg       0.90      0.91      0.90      2895
weighted avg       0.96      0.95      0.96      2895


--- Confusion Matrix ---
[[2138   38    4]
 [   7  319    9]
 [   5   70  305]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/ablation/withoutAttn_confusion_matrix.png


#### 2. SE 블록 제거

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 128 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/ablation_test/ABL_se_off_bs128_lr0.001_20251129-144330
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=0.7207 val_loss=0.4957 val_acc=81.51% val_f1=0.7344 lr=1.000e-03 (344.2s)
Epoch 002 | train_loss=0.4928 val_loss=0.3604 val_acc=86.26% val_f1=0.7873 lr=1.000e-03 (342.5s)
Epoch 003 | train_loss=0.4023 val_loss=0.4450 val_acc=82.46% val_f1=0.7631 lr=1.000e-03 (344.1s)
Epoch 004 | train_loss=0.3718 val_loss=0.7312 val_acc=73.26% val_f1=0.6759 lr=1.000e-03 (334.3s)
Epoch 005 | train_loss=0.3351 val_loss=0.2394 val_acc=91.10% val_f1=0.8417 lr=1.000e-03 (322.8s)
Epoch 006 | train_loss=0.3263 val_loss=0.2927 val_acc=89.50% val_f1=0.8319 lr=1.000e-03 (341.4s)
Epoch 007 | train_loss=0.3131 val_loss=0.1774 val_acc=93.61% val_f1=0.8677 lr=1.000e-03 (343.5s)
Epoch 008 | train_loss=0.3068 val_loss=0.2900 val_acc=89.16% val_f1=0.8238 lr=1.000e-03 (354.4s)
Epoch 009 | train_loss=0.2

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model resseattn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/ablation_test/ABL_se_off_bs128_lr0.001_20251129-144330/best_ep015.pt \
  --batch_size 128 \
  --num_classes 3 \
  --cm_path results/ablation/withoutSE_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : resseattn
===== TEST RESULTS =====
Accuracy   : 0.9554
Precision  : 0.8982
Recall     : 0.9065
F1 Score   : 0.9016

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.99      0.98      0.99      2180
           1       0.80      0.87      0.83       335
           2       0.91      0.86      0.88       380

    accuracy                           0.96      2895
   macro avg       0.90      0.91      0.90      2895
weighted avg       0.96      0.96      0.96      2895


--- Confusion Matrix ---
[[2146   30    4]
 [  12  293   30]
 [   9   44  327]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/ablation/withoutSE_confusion_matrix.png


#### 3. Residual Block의 Skip_Connection 제거

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 128 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/ablation_test/ABL_skip_connection_off_bs128_lr0.001_20251130-045250
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=1.0345 val_loss=0.8748 val_acc=79.87% val_f1=0.6990 lr=1.000e-03 (338.2s)
Epoch 002 | train_loss=0.7568 val_loss=0.5640 val_acc=85.01% val_f1=0.7725 lr=1.000e-03 (345.2s)
Epoch 003 | train_loss=0.5470 val_loss=0.3868 val_acc=87.69% val_f1=0.8088 lr=1.000e-03 (341.9s)
Epoch 004 | train_loss=0.4319 val_loss=0.5245 val_acc=78.62% val_f1=0.7308 lr=1.000e-03 (336.0s)
Epoch 005 | train_loss=0.3822 val_loss=0.2093 val_acc=93.09% val_f1=0.8646 lr=1.000e-03 (329.5s)
Epoch 006 | train_loss=0.3581 val_loss=0.2386 val_acc=91.32% val_f1=0.8480 lr=1.000e-03 (334.9s)
Epoch 007 | train_loss=0.3343 val_loss=0.1891 val_acc=93.13% val_f1=0.8583 lr=1.000e-03 (335.0s)
Epoch 008 | train_loss=0.3215 val_loss=0.2001 val_acc=93.30% val_f1=0.8648 lr=1.000e-03 (336.1s)
Epoch 009 | t

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model resseattn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/ablation_test/ABL_skip_connection_off_bs128_lr0.001_20251130-045250/best_ep018.pt \
  --batch_size 128 \
  --num_classes 3 \
  --cm_path results/ablation/without_SkipConnection_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : resseattn
===== TEST RESULTS =====
Accuracy   : 0.9606
Precision  : 0.9108
Recall     : 0.9185
F1 Score   : 0.9098

--- Classification Report ---
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      2180
           1       0.78      0.96      0.86       335
           2       0.96      0.81      0.88       380

    accuracy                           0.96      2895
   macro avg       0.91      0.92      0.91      2895
weighted avg       0.97      0.96      0.96      2895


--- Confusion Matrix ---
[[2152   25    3]
 [   4  320   11]
 [   6   65  309]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/ablation/without_SkipConnection_confusion_matrix.png


#### 4. SE, Spatial Attention 제거

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 128 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/ablation_test/ABL_res_only_bs128_lr0.001_20251201-111058
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=0.7114 val_loss=0.5225 val_acc=80.86% val_f1=0.7249 lr=1.000e-03 (347.7s)
Epoch 002 | train_loss=0.4858 val_loss=0.5017 val_acc=79.40% val_f1=0.7318 lr=1.000e-03 (351.4s)
Epoch 003 | train_loss=0.4012 val_loss=0.3048 val_acc=88.86% val_f1=0.8164 lr=1.000e-03 (344.4s)
Epoch 004 | train_loss=0.3614 val_loss=0.3622 val_acc=86.26% val_f1=0.7919 lr=1.000e-03 (345.8s)
Epoch 005 | train_loss=0.3351 val_loss=0.2023 val_acc=92.74% val_f1=0.8578 lr=1.000e-03 (347.8s)
Epoch 006 | train_loss=0.3354 val_loss=0.2010 val_acc=92.70% val_f1=0.8612 lr=1.000e-03 (346.3s)
Epoch 007 | train_loss=0.3243 val_loss=0.1659 val_acc=94.13% val_f1=0.8802 lr=1.000e-03 (336.1s)
Epoch 008 | train_loss=0.3129 val_loss=0.2568 val_acc=90.41% val_f1=0.8405 lr=1.000e-03 (351.6s)
Epoch 009 | train_loss=0

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model resseattn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/ablation_test/ABL_res_only_bs128_lr0.001_20251201-111058/best_ep015.pt \
  --batch_size 128 \
  --num_classes 3 \
  --cm_path results/ablation/without_Attn/SE_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : resseattn
===== TEST RESULTS =====
Accuracy   : 0.9551
Precision  : 0.9060
Recall     : 0.8966
F1 Score   : 0.9011

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      2180
           1       0.83      0.85      0.84       335
           2       0.90      0.85      0.88       380

    accuracy                           0.96      2895
   macro avg       0.91      0.90      0.90      2895
weighted avg       0.95      0.96      0.95      2895


--- Confusion Matrix ---
[[2157   19    4]
 [  20  284   31]
 [  18   38  324]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/ablation/without_Attn/SE_confusion_matrix.png


##### 5. Depth 줄이기

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.models.train \
  --processed_root /content/crop_processed_data/lettuce_v1 \
  --batch_size 128 \
  --num_workers 2 \
  --epochs 20

/content/drive/MyDrive/Lettuce_disease_diagnosis
[Device] cuda
[Run dir] runs_lettuce/ablation_test/ABL_reduce_depth_bs128_lr0.001_20251202-094430
[Data] Train: 9265 | Val: 2315
Classes: ['0', '10', '9']
Epoch 001 | train_loss=1.0251 val_loss=0.8767 val_acc=75.59% val_f1=0.6619 lr=1.000e-03 (350.0s)
Epoch 002 | train_loss=0.7961 val_loss=0.6742 val_acc=76.16% val_f1=0.6816 lr=1.000e-03 (347.5s)
Epoch 003 | train_loss=0.6795 val_loss=0.5172 val_acc=82.42% val_f1=0.7448 lr=1.000e-03 (345.0s)
Epoch 004 | train_loss=0.6013 val_loss=0.4491 val_acc=86.91% val_f1=0.7873 lr=1.000e-03 (333.3s)
Epoch 005 | train_loss=0.5488 val_loss=0.4230 val_acc=86.52% val_f1=0.7860 lr=1.000e-03 (347.0s)
Epoch 006 | train_loss=0.5135 val_loss=0.3096 val_acc=90.06% val_f1=0.8204 lr=1.000e-03 (351.7s)
Epoch 007 | train_loss=0.4798 val_loss=0.4124 val_acc=84.45% val_f1=0.7721 lr=1.000e-03 (346.6s)
Epoch 008 | train_loss=0.4499 val_loss=0.4580 val_acc=82.29% val_f1=0.7512 lr=1.000e-03 (341.4s)
Epoch 009 | train_lo

In [ ]:
%cd /content/drive/MyDrive/Lettuce_disease_diagnosis
!python -m src.test \
  --model resseattn \
  --data_root /content/crop_processed_data/lettuce_v1/test \
  --ckpt_path runs_lettuce/ablation_test/ABL_reduce_depth_bs128_lr0.001_20251202-094430/best_ep017.pt \
  --batch_size 128 \
  --num_classes 3 \
  --cm_path results/ablation/reduce_depth_confusion_matrix.png

/content/drive/MyDrive/Lettuce_disease_diagnosis
Device: cuda
Model : resseattn
===== TEST RESULTS =====
Accuracy   : 0.9520
Precision  : 0.8957
Recall     : 0.8987
F1 Score   : 0.8964

--- Classification Report ---
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      2180
           1       0.79      0.86      0.83       335
           2       0.91      0.85      0.88       380

    accuracy                           0.95      2895
   macro avg       0.90      0.90      0.90      2895
weighted avg       0.95      0.95      0.95      2895


--- Confusion Matrix ---
[[2144   30    6]
 [  19  289   27]
 [  12   45  323]]

Class Index Mapping:
0 → 0
1 → 10
2 → 9
[INFO] Confusion matrix heatmap saved to: results/ablation/reduce_depth_confusion_matrix.png
